### ISSUE TITLE
Move away from dead upstream toml library

### ISSUE THREAD

**Issue by jonathanspw** [hypershell/hypershell#33]
The toml library is unmaintained upstream and something like tomllib should be used instead.

More info: https://fedoraproject.org/wiki/Changes/DeprecatePythonToml

**Comment by glentner** [comment]
I'll work on swapping out the toml dependency. I'll need to play with both this and CmdKit I think.

**Comment by glentner** [comment]
We might have to make this Python 3.11+ only to allow for use of `libtoml` from the standard library.

**Comment by jonathanspw** [comment]
> We might have to make this Python 3.11+ only to allow for use of `libtoml` from the standard library.

That would be less than ideal for supporting older distros like EL8/9 that default to 3.6 and 3.9 respectively.

**Comment by Conan-Kudo** [comment]
You can use [`tomli`](https://pypi.org/project/tomli/) for older Python versions, as `tomllib` is derived from it.

**Comment by glentner** [comment]
This change has been released in downstream CmdKit (v2.7.6). Updating HyperShell soon.

**Comment by glentner** [comment]
This issue is resolved by [v2.6.1](https://github.com/hypershell/hypershell/releases/tag/2.6.1) (and [v2.6.2](https://github.com/hypershell/hypershell/releases/tag/2.6.2)).
